dotnet/Nerdbank.Streams

src/Directory.Build.props, src/Nerdbank.Streams.Tests/StreamExtensionsTests.cs, src/Nerdbank.Streams/Nerdbank.Streams.csproj, src/Nerdbank.Streams/StreamExtensions.cs
This allows accessing a stream using the pipe API.
These extension methods perform the opposite function to the `PipeStream` class, which converts pipe reader/writer into a Stream.
=> Add UsePipeReader and UsePipeWriter extension methods on Stream

src/Nerdbank.Streams.Tests/StreamExtensionsTests.cs, src/Nerdbank.Streams/StreamExtensions.cs, src/Nerdbank.Streams/Utilities.cs
This means we read the stream only when asked instead of constantly with an async method.
=> Return a custom PipeReader from Stream.UsePipeReader

src/Nerdbank.Streams.Tests/FullDuplexStreamPairTests.cs, src/Nerdbank.Streams.Tests/MultiplexingStreamTests.cs, src/Nerdbank.Streams.Tests/XunitTraceListener.cs, src/Nerdbank.Streams/FullDuplexStream.cs, src/Nerdbank.Streams/PipeExtensions.cs, src/Nerdbank.Streams/PipeStream.cs
The PairedStream wasn't particularly optimized for netcoreapp2.1, but other streams we have implemented are. Rather than maintain so many independent streams, this removes the custom PairedStream implementation in favor of reusing our Pipe-as-Stream code, which already had most of the optimizations we need.
This introduces a requirement that FullDuplexStream paired streams must be flushed after writing before the reader can read it. This is a behavioral breaking change, but is consistent with other streams and actually makes this stream more useful in testing environments since it better emulates most other types of streams (e.g. if product code is failing to flush, that bug will now show up with the new FullDuplexStream behavior).
=> Replace FullDuplexStream+PairedStream with reuse of other streams

src/Nerdbank.Streams/Nerdbank.Streams.csproj
This mitigates a security vulnerability in the 4.5.0 version.
=> Use System.IO.Pipelines 4.5.1

src/Directory.Build.props, src/IsolatedTestHost/IsolatedTestHost.csproj, src/Nerdbank.Streams.Interop.Tests/Nerdbank.Streams.Interop.Tests.csproj, src/Nerdbank.Streams.Tests/BufferWriterStreamTests.cs, src/Nerdbank.Streams.Tests/Nerdbank.Streams.Tests.csproj, src/Nerdbank.Streams.Tests/Nerdbank.Streams.Tests.ruleset, src/Nerdbank.Streams.Tests/ProcessJobTracker.cs, src/Nerdbank.Streams.Tests/ReadOnlySequenceStreamTests.cs, src/Nerdbank.Streams/BufferWriterStream.cs, src/Nerdbank.Streams/HalfDuplexStream.cs, src/Nerdbank.Streams/Nerdbank.Streams.csproj, src/Nerdbank.Streams/PipeExtensions.cs, src/Nerdbank.Streams/PipeStream.cs, src/Nerdbank.Streams/ReadOnlySequenceStream.cs, src/Nerdbank.Streams/StreamPipeReader.cs, src/Nerdbank.Streams/Substream.cs
- Add missing .ConfigureAwait(false) for all awaits
- Override more Stream methods on .NET Core 2.1 
Closes #43
=> Override more Stream methods on .NET Core 2.1 

src/Nerdbank.Streams.Tests/SequenceTests.cs, src/Nerdbank.Streams/Sequence`1.cs
This for example allows serializers to set a large value so that the result is a few large arrays instead of many tiny ones.
Closes #52
=> Add Sequence<T>.MinimumSpanLength

azure-pipelines.yml, azure-pipelines/testfx.yml, src/Directory.Build.props, src/Nerdbank.Streams.Tests/BufferWriterStreamTests.cs, src/Nerdbank.Streams.Tests/FullDuplexStreamCombineTests.cs, src/Nerdbank.Streams.Tests/Nerdbank.Streams.Tests.csproj, src/Nerdbank.Streams.Tests/ReadOnlySequenceStreamTests.cs, src/Nerdbank.Streams.Tests/StreamUsePipeReaderTests.cs, src/Nerdbank.Streams.Tests/StreamUsePipeWriterTests.cs, src/Nerdbank.Streams.Tests/StreamUseStrictPipeReaderTests.cs, src/Nerdbank.Streams.Tests/StreamUseStrictPipeWriterTests.cs, src/Nerdbank.Streams/BufferWriterStream.cs, src/Nerdbank.Streams/FullDuplexStream.cs, src/Nerdbank.Streams/MultiplexingProtocolException.cs, src/Nerdbank.Streams/Nerdbank.Streams.csproj, src/Nerdbank.Streams/ReadOnlySequenceStream.cs, src/Nerdbank.Streams/Substream.cs, src/global.json
Also revise our #if directives to make it clearer that they'll behave when adding more targets in the future.
Also test on netcoreapp2.2
The net472 target is equivalent to the net46 one, except it compiles against newer reference assemblies and thus a few dependencies are dropped, allowing for higher performance since facade assemblies don't have to load at runtime.
=> Add net472 target

doc/PrefixingBufferWriter.md, src/Nerdbank.Streams.Tests/PrefixingBufferWriterTests.cs, src/Nerdbank.Streams/PrefixingBufferWriter`1.cs
Refines API for PrefixingBufferWriter, removing the need for the caller to allocate memory for the prefix just to pass it into Complete when it could just as easily initialize the header memory directly in-place.
=> Expose memory behind Prefix for direct writing

.gitignore, src/Nerdbank.Streams.Benchmark/BenchmarkConfig.cs, src/Nerdbank.Streams.Benchmark/Nerdbank.Streams.Benchmark.csproj, src/Nerdbank.Streams.Benchmark/Nerdbank.Streams.Benchmark.ruleset, src/Nerdbank.Streams.Benchmark/Program.cs, src/Nerdbank.Streams.Benchmark/SequenceBenchmark.cs, src/Nerdbank.Streams.Tests/SequenceTests.cs, src/Nerdbank.Streams.sln, src/Nerdbank.Streams/Sequence`1.cs
This improves `Sequence<T>` performance by 24-33%. And more wins may be possible with a fix for #51.
Closes #53
=> Sequence<T> perf enhancements

src/Nerdbank.Streams.Tests/MockArrayPool`1.cs, src/Nerdbank.Streams.Tests/MockMemoryPool`1.cs, src/Nerdbank.Streams.Tests/PrefixingBufferWriterTests.cs, src/Nerdbank.Streams.Tests/SequenceTests.cs, src/Nerdbank.Streams/Sequence`1.cs
This is the new default.
It reduces GC pressure since renting arrays no longer incurs an IMemoryOwner<T> allocation.
It also improves performance significantly: 14-32%
Closes #51
=> Add support for ArrayPool<T> to Sequence<T>

README.md, doc/BufferTextWriter.md, doc/SequenceTextReader.md, src/Nerdbank.Streams.Tests/BufferTextWriterTests.cs, src/Nerdbank.Streams.Tests/SequenceTextReaderTests.cs, src/Nerdbank.Streams/BufferTextWriter.cs, src/Nerdbank.Streams/SequenceTextReader.cs, src/Nerdbank.Streams/Utilities.cs
These remove the need for AsStream() and StreamReader/StreamWriter to read and write text from ReadOnlySequence<byte> and IBufferWriter<byte> and dramatically reduce GC pressure that otherwise apply when using such adapters.
`BufferTextWriter` adapts `IBufferWriter<byte>` to be access as a `TextWriter`.
`SequenceTextReader` adapts `ReadOnlySequence<byte>` to be access as a `TextReader`.
=> Add BufferTextWriter and SequenceTextReader

src/Nerdbank.Streams.Tests/MockInterruptedFullDuplexStream.cs, src/Nerdbank.Streams.Tests/MockInterruptedWebSocket.cs, src/Nerdbank.Streams.Tests/PipeExtensionsTests.cs, src/Nerdbank.Streams/PipeExtensions.cs
Closes #75.
I have also added tests for exception propagation in order to ensure that I did not break existing behaviors. I needed to introduce a `Stream` mock because in a normal situation `Stream.Read()` does not fail while `Stream.Write()` does (for example "connection lost").
I do not have any idea how to directly test this in unit tests, because the `UnobservedTaskException` event is global and completely avoiding the `UnobservedTaskException` event would be too restrictive for tests.
=> PipeExtensions to avoid triggering the UnobservedTaskException event

src/Nerdbank.Streams/MultiplexingStream.Channel.cs, src/Nerdbank.Streams/MultiplexingStream.cs, src/Nerdbank.Streams/Nerdbank.Streams.csproj, src/Nerdbank.Streams/Nerdbank.Streams.ruleset
Use .ConfigureAwait(false) everywhere and rename a few Async methods.
Fixes #79
=> Correct the path to the .ruleset file used by library

src/Nerdbank.Streams/MultiplexingStream.cs
Similar fix to what we had to [fix in streamjsonrpc][1] a while ago.
[1]: https://github.com/microsoft/vs-streamjsonrpc/pull/176
=> Flush stream within semaphore

src/Nerdbank.Streams.Tests/MultiplexingStreamTests.cs, src/Nerdbank.Streams.Tests/Nerdbank.Streams.Tests.ruleset, src/Nerdbank.Streams.Tests/TestBase.cs, src/Nerdbank.Streams.Tests/XunitTraceListener.cs, src/Nerdbank.Streams/MultiplexingStream.Channel.cs, src/Nerdbank.Streams/MultiplexingStream.FrameHeader.cs, src/Nerdbank.Streams/MultiplexingStream.cs, src/Nerdbank.Streams/Nerdbank.Streams.ruleset
Fix Channel.Dispose to handle pending sends/receives
Frames received for a channel after its local disposal are now discarded. Any pending write+flush to the channel's PipeWriter is canceled so as to avoid plugging up the multiplexing stream when the disposed channel hasn't drained its own pipe.
When a Channel is disposed after writing and flushing bytes, a Channel that manages its own Pipe will complete transmission before actual disposal. Channels initialized with an ExistingPipe will terminate without guaranteeing that writes are completed, since we don't have any way of knowing when writes are done if the writer is not completed (which is our recommended path for disposing channels).
Fixes #88
=> Fix Channel.Dispose to handle pending sends/receives

src/Nerdbank.Streams/Nerdbank.Streams.csproj, src/global.json
This target isn't necessary (we don't compile any differently for it compared to netstandard2.0).
I also remove the unnecessary MSBuild.Sdk.Extras and a packageref that never compiled since we removed netstandard1.6 support.
=> Remove net472 target

src/Nerdbank.Streams.Tests/NestedPipeReaderTests.cs, src/Nerdbank.Streams/NestedPipeReader.cs, src/Nerdbank.Streams/Strings.Designer.cs, src/Nerdbank.Streams/Strings.resx
Also no-op instead of throw for OnWriterCompleted.
=> Add support for PipeReader.Complete

src/Nerdbank.Streams/MultiplexingStream.cs
=> Protect mxstream's underlying stream against concurrent disposal

src/Nerdbank.Streams.Interop.Tests/Nerdbank.Streams.Interop.Tests.csproj, src/Nerdbank.Streams.Tests/Nerdbank.Streams.Tests.csproj, src/Nerdbank.Streams/Nerdbank.Streams.csproj
This gets us to a version that can compile with the .NET Native tool chain.
=> Update vs-threading dependency

src/Nerdbank.Streams.Tests/MultiplexingStreamPerfTests.cs, src/Nerdbank.Streams/MultiplexingStream.Channel.cs, src/Nerdbank.Streams/PipeExtensions.cs, src/Nerdbank.Streams/PipeStream.cs, src/Nerdbank.Streams/Utilities.cs
This fixes a bug where the last Channel transmission can be truncated.
=> Avoid accessing ReadResult.Buffer after PipeReader.AdvanceTo

src/Nerdbank.Streams.Tests/MonitoringStreamTests.cs, src/Nerdbank.Streams.Tests/SubstreamTests.cs, src/Nerdbank.Streams/MonitoringStream.cs
=> Add MonitoringStream.DidFlush event

src/Nerdbank.Streams.Tests/SequenceTests.cs, src/Nerdbank.Streams/Sequence`1.cs
This is consistent with PipeReader.AdvanceTo behavior.
=> Fix Sequence.AdvanceTo(default) so it simply no-ops

src/Nerdbank.Streams.Tests/MultiplexingStreamTests.cs, src/Nerdbank.Streams.Tests/PipeExtensionsTests.cs, src/Nerdbank.Streams.Tests/TestBase.cs, src/Nerdbank.Streams/PipeExtensions.cs
=> Fix Stream disposal when ReadAsync ignores CancellationToken

src/Nerdbank.Streams.Tests/SequenceTests.cs, src/Nerdbank.Streams/Sequence`1.cs
If the `T` in `Sequence<T>` is a struct that references objects, then recycled arrays may not immediately release references to allow objects to be GC'd. This change fixes that to clear all non-primitive structs as well as reference types stored in the sequence.
Strictly speaking, *any* blittable struct needn't be cleared, but I can't find the API to test whether a struct is blittable at the moment, so I'm settling for the `Type.IsPrimitive` check.
Thanks to @bboyle1234 for pointing out the need for this change in https://github.com/AArnott/Nerdbank.Streams/commit/caee1d18457ca723f591f990783b8ffd00170987#commitcomment-38032369.
=> Clear references that may be in structs from Sequence<T>

src/Nerdbank.Streams.Tests/SequenceTextReaderTests.cs, src/Nerdbank.Streams/SequenceTextReader.cs
=> Fix SequenceTextReader decoding of surrogate pairs at the buffer boundary

src/Nerdbank.Streams.Tests/SequenceTests.cs, src/Nerdbank.Streams/Sequence`1.cs
=> Fix reference clearing in `Sequence<T>.Reset()`

doc/MultiplexingStream.md, src/Nerdbank.Streams.Interop.Tests/Program.cs, src/Nerdbank.Streams.Tests/MultiplexingStreamOptionsTests.cs, src/Nerdbank.Streams.Tests/MultiplexingStreamSeededChannelTests.cs, src/Nerdbank.Streams.Tests/MultiplexingStreamTests.cs, src/Nerdbank.Streams.Tests/MultiplexingStreamV3Tests.cs, src/Nerdbank.Streams.Tests/TestBase.cs, src/Nerdbank.Streams/MultiplexingStream.Channel.cs, src/Nerdbank.Streams/MultiplexingStream.Formatters.cs, src/Nerdbank.Streams/MultiplexingStream.FrameHeader.cs, src/Nerdbank.Streams/MultiplexingStream.Options.cs, src/Nerdbank.Streams/MultiplexingStream.QualifiedChannelId.cs, src/Nerdbank.Streams/MultiplexingStream.cs, src/Nerdbank.Streams/Strings.Designer.cs, src/Nerdbank.Streams/Strings.resx, src/Nerdbank.Streams/netcoreapp2.1/PublicAPI.Unshipped.txt, src/Nerdbank.Streams/netcoreapp3.1/PublicAPI.Unshipped.txt, src/Nerdbank.Streams/netstandard2.0/PublicAPI.Unshipped.txt, src/nerdbank-streams/src/Channel.ts, src/nerdbank-streams/src/FrameHeader.ts, src/nerdbank-streams/src/MultiplexingStream.ts, src/nerdbank-streams/src/MultiplexingStreamFormatters.ts, src/nerdbank-streams/src/MultiplexingStreamOptions.ts, src/nerdbank-streams/src/QualifiedChannelId.ts, src/nerdbank-streams/src/index.ts, src/nerdbank-streams/src/tests/MultiplexingStream.Interop.spec.ts, src/nerdbank-streams/src/tests/MultiplexingStream.SeededChannels.spec.ts, src/nerdbank-streams/src/tests/MultiplexingStream.spec.ts, src/nerdbank-streams/yarn.lock
This allows two v3 mxstream endpoints to 'hot wire' any number of channels as pre-negotiated so they can be used immediately without exchanging network packets.
=> Add support for seeded channels to MultiplexingStream

src/Nerdbank.Streams.Tests/MultiplexingStreamTests.cs, src/Nerdbank.Streams/MultiplexingStream.Channel.cs
When an ExistingPipe is given for a MultiplexingStream.Channel, it's very important that the Channel *complete* both the reader and the writer on that ExistingPipe so that it shuts down, releases memory, etc. When this pipe is backed by a `Stream`, it's particularly important to do this so that any held resources are released.
The PR fixes a bug where the `ExistingPipe.Input` wouldn't be completed because we were in the middle of a `ReadAsync` call on it, which would not complete because no more data was coming. We need to break out of that `ReadAsync` call so we notice the rest of the channel is shutdown and complete that reader, regardless of whether more data is coming (since the channel is gone anyway).
=> Shutdown ExistingPipe streams on channel disposal

src/Nerdbank.Streams/Nerdbank.Streams.csproj
The Substream class implements IAsyncDisposable, and as such, cannot be used from C# 8 in a `using` block unless both assemblies that define `IAsyncDisposable` are referenced.
=> Fix compiler error when users of `Substream` do not reference our ref assemblies

src/Nerdbank.Streams.Tests/MultiplexingStreamV2Tests.cs, src/Nerdbank.Streams/MultiplexingStream.cs
This quietly skips transmission of the `ContentProcessed` frame when it follows a `ChannelTerminated` frame.
We were already quietly ignoring incoming `ChannelProcessed` when it was for a channel that the receiving side didn't recognize as open:
https://github.com/AArnott/Nerdbank.Streams/blob/9d23cca0219f5ed800b3c34f499f9a947e11d339/src/Nerdbank.Streams/MultiplexingStream.cs#L900
And in fact there's a bigger window of opportunity here: we only detected out of order transmission of frames when we had transmitted `ChannelTerminated` but had not yet *received* `ChannelTerminated` for that same channel. After these termination frames went both ways, we forget that the channel ever existed, and if the `ContentProcessed` frame came after that, it would have been transmitted.
So clearly there's …
=> Avoid MultiplexingStream self-destruct when ContentProcessed follows ChannelTerminated

src/Nerdbank.Streams/MultiplexingStream.cs
=> Suppress critical events about ObjectDisposedException when we are disposed already

src/Nerdbank.Streams.Tests/PipeExtensionsTests.cs, src/Nerdbank.Streams.Tests/ReadOnlySequenceStreamTests.cs, src/Nerdbank.Streams/PipeExtensions.cs, src/Nerdbank.Streams/ReadOnlySequenceStream.cs, src/Nerdbank.Streams/StreamExtensions.cs, src/Nerdbank.Streams/netcoreapp2.1/PublicAPI.Unshipped.txt, src/Nerdbank.Streams/netcoreapp3.1/PublicAPI.Unshipped.txt, src/Nerdbank.Streams/netstandard2.0/PublicAPI.Unshipped.txt
- PipeReaderStream.Dispose should only invoke callback once
- Add `PipeReader.AsPrebufferedStreamAsync` extension method
=> Add PipeReader.AsPrebufferedStreamAsync extension method

src/Nerdbank.Streams.Tests/MultiplexingStreamTests.cs, src/Nerdbank.Streams/DuplexPipe.cs, src/Nerdbank.Streams/PipeExtensions.cs
The added test for one-way mx channel already passed, but when run in the debugger the test reveals the 2 first chance exceptions that were thrown before the fix is applied.
Closes #252
=> Avoid 1st chance exceptions in one-way mxstream channels

src/Nerdbank.Streams.Tests/NestedStreamTests.cs, src/Nerdbank.Streams/NestedStream.cs
It's possible for `NestedStream.Read` to issue a 0-length read to the underlying stream (e.g. when at the end of the stream).
Some streams behave incorrectly when you issue 0-length reads: https://github.com/dotnet/runtime/issues/52009 .
This PR prevents such calls by just returning 0 if a zero-length read would be issued.
=> NestedStream: Avoid zero-length reads

src/Nerdbank.Streams.Tests/NestedStreamTests.cs, src/Nerdbank.Streams/NestedStream.cs
The current implementation would throw, but the docs indicate the property should return `false`. (The other `Can*` properties on `NestedStream` correclty implement this behavior.)
=> NestedStream: CanSeek should return false when disposed

src/Nerdbank.Streams.Tests/MultiplexingStreamOptionsTests.cs, src/Nerdbank.Streams.Tests/MultiplexingStreamTests.cs, src/Nerdbank.Streams/MultiplexingStream.Options.cs, src/Nerdbank.Streams/MultiplexingStream.cs, src/Nerdbank.Streams/Strings.Designer.cs, src/Nerdbank.Streams/Strings.resx, src/Nerdbank.Streams/netcoreapp2.1/PublicAPI.Unshipped.txt, src/Nerdbank.Streams/netcoreapp3.1/PublicAPI.Unshipped.txt, src/Nerdbank.Streams/netstandard2.0/PublicAPI.Unshipped.txt
This allows `MultiplexingStream.ChannelOffered` handlers to be added before listening has started, thereby mitigating a race condition with incoming channel offers immediately after the connection is created.
Closes #345
=> Add `MultiplexingStream.Options.StartSuspended` property

src/Nerdbank.Streams.Tests/MultiplexingStreamTests.cs, src/Nerdbank.Streams/MultiplexingStream.cs
This fixes #414, which is a hang that occurs when the `CancellationToken` passed to `MultiplexingStream.CreateAsync` is cancelled after `CreateAsync` has completed.
=> Do not propagate a CancellationToken from a method arg to a long-lived state machine

src/Nerdbank.Streams/Nerdbank.Streams.csproj
The reference brings in legacy 4.3.0 packages.
=> Remove unnecessary reference to System.Net.WebSockets

src/Nerdbank.Streams/MultiplexingStream.Channel.cs, src/Nerdbank.Streams/MultiplexingStream.cs, src/Nerdbank.Streams/UnownedPipeReader.cs, test/Nerdbank.Streams.Tests/MultiplexingStreamTests.cs
While this is a good change for stability, it probably only impacts the runtime functionality of the product (both for good and ill via the breaking change) for those who call `MultiplexingStream.Channel.Dispose`, which is generally discouraged anyway.
Fix #488
=> Fix disposal thread safety

src/Nerdbank.Streams.Tests/MultiplexingStreamV2Tests.cs, src/Nerdbank.Streams.Tests/TestBase.cs, src/Nerdbank.Streams/MultiplexingStream.Channel.cs
The overrides we had for this method simply delegated to the underlying pipe, which omitted advancing the limited backpressure 'window' as reading took place. This led to a hang when the data to be read exceeded the window size. Since the default implementation of `CopyToAsync` in the base class is simply a loop that calls `ReadAsync` and `AdvanceTo`, we can just delete our overrides. Our `AdvanceTo` method includes a window advancement.
Fixes #506
=> Fix hang in `MultiplexingStream.Channel.Input.CopyToAsync`

src/Nerdbank.Streams/FullDuplexStream.cs, test/Nerdbank.Streams.Tests/FullDuplexStreamPairTests.cs
The base implementation of Stream does not allow concurrent BeginRead and BeginWrite operations.
A NetworkStream overrides these methods to fully support asynchronous operations.
Therefore I simply forward the calls to the underlying readable and writable streams to achieve the same behavior.
This will fix https://github.com/microsoft/vs-streamjsonrpc/issues/822
=> Support concurrent BeginRead and BeginWrite in CombinedStream

version.json
Removes the `alpha` tag from Nerbank.Streams version for version stabilization with the release of 17.4 Preview 3
=> Removed unstable tag from version 2.9-alpha

src/Nerdbank.Streams/ReadOnlySequenceStream.cs, test/Nerdbank.Streams.Tests/ReadOnlySequenceStreamTests.cs
The ReadOnlySequenceStream Seek method does not function correctly with SeekOrigin.End and a negative offset. It seeks relative to the current position instead of the end of the stream.
This pull request fixes this issue and updates the unit test. The test did not catch the error because the stream was positioned at the end when testing this method.
=> Fix of the ReadOnlySequenceStream Seek method

src/nerdbank-streams/src/MultiplexingStream.ts, src/nerdbank-streams/src/tests/MultiplexingStream.spec.ts, src/nerdbank-streams/src/tests/Timeout.ts
We had been abandoning them up to this point. Once fixing that, it exposed another issue with an unobserved promise rejection in our tests which I fix as well.
=> Reject acceptChannel promises on disposal

src/Nerdbank.Streams/MultiplexingStream.Channel.cs
Also move some method calls outside of a lock.
=> Reduce use of `Task.Run`

.config/dotnet-tools.json, Directory.Packages.props, azure-pipelines/Get-SymbolFiles.ps1
- Fix symbol file selection for R2R outputs
- Bump dotnet-coverage to 17.7.2
- Bump StyleCop.Analyzers.Unstable from 1.2.0.435 to 1.2.0.507 (#207)
- Bump dotnet-coverage from 17.7.2 to 17.7.3 (#208)
=> Merge latest Library.Template

src/Nerdbank.Streams/MultiplexingStream.cs, src/nerdbank-streams/src/MultiplexingStream.ts, src/nerdbank-streams/src/tests/MultiplexingStream.spec.ts, test/Nerdbank.Streams.Tests/MultiplexingStreamTests.cs
Also add tests and API docs to clarify that `acceptChannelAsync` will accept offers for anonymous channels if the channel name is empty.
=> Fix TS mxstream acceptChannelAsync for empty channel names

test/Nerdbank.Streams.Tests/Nerdbank.Streams.Tests.csproj
Tests on mono were failing far too frequently for the pipeline stability we want.
=> Skip testing on mono

src/Nerdbank.Streams/Nerdbank.Streams.csproj
Microsoft.Bcl.AsyncInterfaces provides API that is already inbox on netstandard2.1. Don't reference the package for that framework to reduce the dependency graph.
=> Don't reference M.Bcl.AsyncInterfaces on netstandard2.1

src/Nerdbank.Streams/PipeExtensions.cs
=> Document that `WebSocket` boundaries are useless with using the Pipelines API

src/Nerdbank.Streams/MultiplexingStream.Options.cs
This was between 5ms -> 15ms during VS startup on the UI thread.
=> Avoid loading strings unless needed

src/nerdbank-streams/src/Channel.ts, src/nerdbank-streams/src/Utilities.ts, src/nerdbank-streams/src/tests/MultiplexingStream.spec.ts
When the node.js implementation of a `MultiplexingStream` channel receives more data than the highWatermark (16KB) limit, a flowing stream stops flowing permanently, blocking all communication in that direction.
This fixes the problem by calling `resume()` on the stream when flowing has been stopped by that particular data buffer.
=> Fix node.js stream blockage in mxstream channels

src/Nerdbank.Streams/MonitoringStream.cs, test/Nerdbank.Streams.Tests/MonitoringStreamTests.cs
=> Fix `DidReadSpan` and `DidReadMemory` events on `MonitoringStream` to not over-report buffer read

src/Nerdbank.Streams/MonitoringStream.cs, test/Nerdbank.Streams.Tests/MonitoringStreamTests.cs, test/Nerdbank.Streams.Tests/SubstreamTests.cs
Although it was a bug fix, #769 was also a breaking change in a minor release, and was noticed by at least one user. The test changes are not reverted, but rather modified to verify the original behavior.
Fixes #856
=> Revert the bug fix in MonitoringStream `DidRead` and `DidWrite` events

src/Nerdbank.Streams/MultiplexingStream.cs
Instead, we log it the same way we log unexpected `ContentProcessed` messages.
=> Avoid throwing `KeyNotFoundException` from `MultiplexingStream.OnContentAsync`

src/Nerdbank.Streams/SimplexStream.cs, src/Nerdbank.Streams/net8.0/PublicAPI.Unshipped.txt, src/Nerdbank.Streams/netstandard2.0/PublicAPI.Unshipped.txt, src/Nerdbank.Streams/netstandard2.1/PublicAPI.Unshipped.txt, test/Nerdbank.Streams.Tests/SimplexStreamTests.cs
Add exception argument to SimplexStream.CompleteWriting.
Allows to make stream invalid and potentially make problems on the other side more visible.
```csharp
writer.CompleteWriting(new Exception("Something went wrong my friend!"));
...
try
{
reader.Read(buffer);
}
catch (Exception ex)
{
Console.WriteLine("Potentially something went wrong on the other side!");
}
```
=> add feature to set error when using CompleteWriting
