src/Nerdbank.FullDuplexStream.Tests/FullDuplexStreamTests.cs
src/Nerdbank.FullDuplexStream/FullDuplexStream.cs

Throw ObjectDisposedException after disposal

---

src/IsolatedTestHost/ExitCodes.cs
src/IsolatedTestHost/IsolatedTestHost.csproj
src/IsolatedTestHost/IsolatedTestHost.ruleset
src/IsolatedTestHost/Program.cs
src/IsolatedTestHost/Properties/launchSettings.json
src/IsolatedTestHost/TestOutputHelper.cs
src/Nerdbank.Streams.Tests/HalfDuplexStreamTests.cs
src/Nerdbank.Streams.Tests/LanguageExtensions.cs
src/Nerdbank.Streams.Tests/MultiplexingStreamBasicTests.cs
src/Nerdbank.Streams.Tests/MultiplexingStreamPerfTests.cs
src/Nerdbank.Streams.Tests/MultiplexingStreamTests.cs
src/Nerdbank.Streams.Tests/Nerdbank.Streams.Tests.csproj
src/Nerdbank.Streams.Tests/TestBase.cs
src/Nerdbank.Streams.Tests/XunitTraceListener.cs
src/Nerdbank.Streams.sln
src/Nerdbank.Streams/MultiplexingProtocolException.cs
src/Nerdbank.Streams/MultiplexingStream.Channel.cs
src/Nerdbank.Streams/MultiplexingStream.ChannelStream.cs
src/Nerdbank.Streams/MultiplexingStream.ControlCode.cs
src/Nerdbank.Streams/MultiplexingStream.FrameHeader.cs
src/Nerdbank.Streams/MultiplexingStream.cs
src/Nerdbank.Streams/Nerdbank.Streams.csproj
src/Nerdbank.Streams/Polyfill/TraceSource.cs
src/Nerdbank.Streams/Utilities.cs
src/Nerdbank.Streams/WebSocketStream.cs

Add multiplexing stream

---

src/Nerdbank.Streams.Tests/SequenceTests.cs
src/Nerdbank.Streams/Sequence`1.cs
src/stylecop.json

This is an early iteration for early design review and other comments.

Add Sequence<T> with tests

---

README.md
doc/MonitoringStream.md
src/Nerdbank.Streams.Tests/MonitoringStreamTests.cs
src/Nerdbank.Streams/MonitoringStream.cs

Add MonitoringStream

---

doc/AsStream.md
src/Nerdbank.Streams.Tests/ReadOnlySequenceStreamTests.cs
src/Nerdbank.Streams/ReadOnlySequenceStream.cs
src/Nerdbank.Streams/StreamExtensions.cs

Add ReadOnlySequence<byte>.AsStream() extension method

---

README.md
doc/Substream.md
src/Nerdbank.Streams.Tests/SubstreamTests.cs
src/Nerdbank.Streams/MultiplexingStream.FrameHeader.cs
src/Nerdbank.Streams/StreamExtensions.cs
src/Nerdbank.Streams/Substream.cs
src/Nerdbank.Streams/SubstreamReader.cs
src/Nerdbank.Streams/Utilities.cs

Add Stream.[Read|Write]Substream extension methods

---

src/Nerdbank.Streams.Interop.Tests/Nerdbank.Streams.Interop.Tests.csproj
src/Nerdbank.Streams.Interop.Tests/Program.cs
src/nerdbank-streams/package.json
src/nerdbank-streams/src/Channel.ts
src/nerdbank-streams/src/MultiplexingStream.ts
src/nerdbank-streams/src/Utilities.ts
src/nerdbank-streams/src/tests/MultiplexingStream.Interop.spec.ts
src/nerdbank-streams/src/tests/MultiplexingStream.spec.ts
src/nerdbank-streams/src/tests/jsonRpcStreams.ts

* Add message exchange on channel interop tests 
* Add support for anonymous channels
* Add cancellation support

More MultiplexingStream functionality in TypeScript

---

azure-pipelines.yml

Fix code coverage in CI build

---

src/Nerdbank.Streams.Tests/HalfDuplexStreamTests.cs
src/Nerdbank.Streams.Tests/StreamPipeReaderTestBase.cs
src/Nerdbank.Streams.Tests/WebSocketStreamTests.cs
src/Nerdbank.Streams/HalfDuplexStream.cs

* Stop flushing within HalfDuplexStream.WriteAsync
* Implement IBufferWriter<byte> in HalfDuplexStream

HalfDuplexStream writing enhancements

---

src/Nerdbank.Streams/MultiplexingStream.cs

Fix race condition when accepting a channel by name that is canceled

---

azure-pipelines.yml
src/Nerdbank.Streams/Nerdbank.Streams.csproj
src/Nerdbank.Streams/StreamPipeReader.cs
src/global.json

This applies the fix/workaround required for https://github.com/dotnet/sdk/issues/2547

Update System.IO.Pipelines to 4.5.3

---

src/Nerdbank.Streams.Tests/SequenceTests.cs
src/Nerdbank.Streams/Sequence`1.cs

Clear references to ref type T when recycling memory in Sequence<T>

---

src/Nerdbank.Streams/Sequence`1.cs

This increases perf by ~40-45% by minimizing type checks and use of TLS.

Sequence<T> perf improvements

---

src/Nerdbank.Streams/MultiplexingStream.cs

This fixes a multiplexing handshake bug when the streams are stdin/stdout streams which malfunction if flushed before a WriteAsync call has completed.

Avoid write-and-flush without awaiting

---

src/Nerdbank.Streams.Tests/MultiplexingStreamTests.cs
src/Nerdbank.Streams/MultiplexingStream.Channel.cs

Add Channel.MultiplexingStream property

---

src/Nerdbank.Streams.Tests/PipeStreamTests.cs
src/Nerdbank.Streams/PipeExtensions.cs
src/Nerdbank.Streams/PipeStream.cs

Allow PipeStream to dispose without completing pipe

---

azure-pipelines.yml
src/Nerdbank.Streams.Tests/Nerdbank.Streams.Tests.csproj

Fix code coverage

---

azure-pipelines.yml
src/Directory.Build.props
src/Nerdbank.Streams.Tests/Nerdbank.Streams.Tests.csproj
src/global.json

And update the SDK version too

Get solution fully building on Ubuntu 18

---

src/Nerdbank.Streams.Tests/MultiplexingStreamChannelOptionsTests.cs
src/Nerdbank.Streams.Tests/MultiplexingStreamTests.cs
src/Nerdbank.Streams/MultiplexingStream.Channel.cs
src/Nerdbank.Streams/MultiplexingStream.ChannelOptions.cs

Add ability to specify PipeOptions for reader of a Channel

---

README.md
doc/ReadSlice.md
src/Nerdbank.Streams.Tests/NestedPipeReaderTests.cs
src/Nerdbank.Streams/NestedPipeReader.cs
src/Nerdbank.Streams/PipeExtensions.cs

Add PipeReader.ReadSlice extension method

---

src/Nerdbank.Streams.Tests/MultiplexingStreamTests.cs
src/Nerdbank.Streams/MultiplexingStream.Channel.cs

Do not send channel content before offer frame

---

src/Nerdbank.Streams.Tests/MonitoringStreamTests.cs
src/Nerdbank.Streams.Tests/PipeReaderCompletionWatcherTests.cs
src/Nerdbank.Streams.Tests/PipeWriterCompletionWatcherTests.cs
src/Nerdbank.Streams/MonitoringStream.cs
src/Nerdbank.Streams/PipeExtensions.cs
src/Nerdbank.Streams/PipeReaderCompletionWatcher.cs
src/Nerdbank.Streams/PipeWriterCompletionWatcher.cs

Add ways to monitor for stream/pipe completion

---

src/Nerdbank.Streams/MultiplexingStream.cs

Stabilizes DisposeChannel_WhileRemoteEndIsTransmitting test

Avoid failing when a Channel.Dispose race condition occurs

---

src/Nerdbank.Streams.Tests/DuplexPipeTests.cs
src/Nerdbank.Streams.Tests/MultiplexingStreamChannelOptionsTests.cs
src/Nerdbank.Streams.Tests/PipeExtensionsTests.cs
src/Nerdbank.Streams/DuplexPipe.cs
src/Nerdbank.Streams/MultiplexingStream.ChannelOptions.cs
src/Nerdbank.Streams/PipeExtensions.cs
src/Nerdbank.Streams/PipeStream.cs

Allow unwrapping a pipe posing as a stream

---

src/Nerdbank.Streams.Tests/SubstreamTests.cs
src/Nerdbank.Streams/Substream.cs

Fix Substream to flush after final write

---

src/Directory.Build.props
src/Nerdbank.Streams/MonitoringStream.cs
src/Nerdbank.Streams/MultiplexingStream.Channel.cs
src/Nerdbank.Streams/Nerdbank.Streams.csproj
src/Nerdbank.Streams/NestedPipeReader.cs
src/Nerdbank.Streams/StreamExtensions.cs
src/Nerdbank.Streams/Substream.cs

I add the threading analyzers to find the missing ones and guard against regression here.
Fixes #130

Add missing .ConfigureAwait(false) suffixes

---

src/Nerdbank.Streams.Tests/SequenceTests.cs
src/Nerdbank.Streams/Sequence`1.cs

Fix InvalidCastException thrown on empty sequences

---

src/Nerdbank.Streams.Tests/BufferTextWriterTests.cs
src/Nerdbank.Streams/BufferTextWriter.cs

Add Flush to BufferTextWriter.Dispose method

---

src/Nerdbank.Streams.Tests/MockMemoryPool`1.cs
src/Nerdbank.Streams.Tests/SequenceTests.cs
src/Nerdbank.Streams/Sequence`1.cs

Add Sequence<T>.AutoIncreaseMinimumSpanLength

---

src/Nerdbank.Streams/SubstreamReader.cs

Fix SubstreamReader's header read

---

src/Nerdbank.Streams.Tests/SequenceTests.cs
src/Nerdbank.Streams/Nerdbank.Streams.csproj
src/Nerdbank.Streams/Sequence`1.cs

Fix Sequence<T> to work for managed types T

---

src/Nerdbank.Streams/PipeExtensions.cs

Consistently complete with OCE on cancellation

---

.gitmodules
azure-pipelines/build.yml
ext/.editorconfig
global.json
src/Directory.Build.props
src/Nerdbank.Streams.Interop.Tests/Program.cs
src/Nerdbank.Streams.Tests/MultiplexingStreamTests.cs
src/Nerdbank.Streams.Tests/WebSocketStreamTests.cs
src/Nerdbank.Streams/.editorconfig
src/Nerdbank.Streams/FullDuplexStream.cs
src/Nerdbank.Streams/MultiplexingStream.Channel.cs
src/Nerdbank.Streams/MultiplexingStream.Formatters.cs
src/Nerdbank.Streams/MultiplexingStream.FrameHeader.cs
src/Nerdbank.Streams/MultiplexingStream.cs
src/Nerdbank.Streams/Nerdbank.Streams.csproj
src/Nerdbank.Streams/PipeExtensions.cs
src/Nerdbank.Streams/Substream.cs
src/nerdbank-streams/package.json
src/nerdbank-streams/src/Channel.ts
src/nerdbank-streams/src/FrameHeader.ts
src/nerdbank-streams/src/MultiplexingStream.ts
src/nerdbank-streams/src/MultiplexingStreamFormatters.ts
src/nerdbank-streams/src/Utilities.ts
src/nerdbank-streams/tsconfig.json
src/nerdbank-streams/yarn.lock

Use MessagePack for mxstream v2 protocol

---

doc/UsePipe.md

Hi Andrew, 
Apologies I took so long to get this done, I've just got to the end of an intense project at work involving pipes and speeding up a data feed.
Here's an addition to the docs as discussed in https://github.com/AArnott/Nerdbank.Streams/issues/177
I feel the comments should include a discussion of what happens to the pipe when the socket is disposed, and what happens to the socket when the pipe reader or writer is completed. But I didn't feel my knowledge was sufficient to rely on. 
Perhaps the network stream should own the socket in order to pass pipe reader or writer completion on to the socket. In the example code below I have the network stream NOT owning the socket.
Over the past 18 days or so since we last messaged, I've completed some pretty good work that could be related …

Added note about System.Net.Sockets.Socket

---

src/nerdbank-streams/src/MultiplexingStream.ts
src/nerdbank-streams/src/MultiplexingStreamFormatters.ts
src/nerdbank-streams/src/tests/MultiplexingStream.spec.ts

Close open channels from mxstream.dispose()

---

src/Nerdbank.Streams.Interop.Tests/Program.cs
src/Nerdbank.Streams.Tests/MultiplexingStreamTests.cs
src/Nerdbank.Streams.Tests/MultiplexingStreamV2Tests.cs
src/Nerdbank.Streams.Tests/MultiplexingStreamV3Tests.cs
src/Nerdbank.Streams/MultiplexingStream.Channel.cs
src/Nerdbank.Streams/MultiplexingStream.ChannelOfferEventArgs.cs
src/Nerdbank.Streams/MultiplexingStream.Formatters.cs
src/Nerdbank.Streams/MultiplexingStream.FrameHeader.cs
src/Nerdbank.Streams/MultiplexingStream.Options.cs
src/Nerdbank.Streams/MultiplexingStream.QualifiedChannelId.cs
src/Nerdbank.Streams/MultiplexingStream.cs
src/Nerdbank.Streams/netcoreapp2.1/PublicAPI.Unshipped.txt
src/Nerdbank.Streams/netcoreapp3.1/PublicAPI.Unshipped.txt
src/Nerdbank.Streams/netstandard2.0/PublicAPI.Unshipped.txt
src/nerdbank-streams/src/Channel.ts
src/nerdbank-streams/src/FrameHeader.ts
src/nerdbank-streams/src/MultiplexingStream.ts
src/nerdbank-streams/src/MultiplexingStreamFormatters.ts
src/nerdbank-streams/src/QualifiedChannelId.ts
src/nerdbank-streams/src/tests/MultiplexingStream.Interop.spec.ts
src/nerdbank-streams/src/tests/MultiplexingStream.spec.ts

Remove handshake requirement for multiplexing stream

---

src/Nerdbank.Streams/PipeExtensions.cs

Workaround for https://github.com/dotnet/runtime/issues/39902

Avoid crashing .NET Core processes while canceling async I/O

---

src/nerdbank-streams/.gitignore
src/nerdbank-streams/gulpfile.ts
src/nerdbank-streams/package.json

Fix js->ts maps

---

azure-pipelines/Convert-PDB.ps1

The loss of a myget feed broke builds.

Fix build break

---

src/Nerdbank.Streams/MultiplexingStream.cs

Do not dispose of and write to PipeWriter concurrently

---

src/Nerdbank.Streams/PipeExtensions.cs
src/Nerdbank.Streams/Strings.Designer.cs
src/Nerdbank.Streams/Strings.resx

Honor writer cancellation/completion in LinkToAsync

---

src/Nerdbank.Streams.Tests/MultiplexingStreamTests.cs
src/Nerdbank.Streams/MultiplexingStream.cs

Block transmission of frames regarding terminated channels
Fixes #209

Block transmission of frames regarding terminated channels

---

azure-pipelines/Darwin.runsettings
azure-pipelines/Linux.runsettings
azure-pipelines/Windows_NT.runsettings
azure-pipelines/artifacts/testResults.ps1
global.json
src/.editorconfig
src/Nerdbank.Streams/MultiplexingStream.Formatters.cs
src/Nerdbank.Streams/MultiplexingStream.cs

Protect thread-safety in the V1Formatter for reading vs. disposal

---

azure-pipelines/build.yml

AzP doesn't offer 16.04 any more.

Switch to ubuntu 18.04 on AzP

---

src/nerdbank-streams/src/Channel.ts
src/nerdbank-streams/src/MultiplexingStream.ts
src/nerdbank-streams/src/MultiplexingStreamOptions.ts
src/nerdbank-streams/src/Utilities.ts

Don't leak promises, nor throw on mxstream shutdown

Fix channel disposal on mx stream teardown

---

src/Nerdbank.Streams/SpanPolyfillExtensions.cs
src/Nerdbank.Streams/StreamPipeReader.cs
src/Nerdbank.Streams/netstandard2.0/PublicAPI.Unshipped.txt
src/Nerdbank.Streams/netstandard2.1/PublicAPI.Unshipped.txt
test/Nerdbank.Streams.Tests/StreamUseStrictPipeReaderTests.cs

Expose StreamPipeReader with sync Read method

---

.gitignore
Directory.Build.props
azure-pipelines/Get-CodeCovTool.ps1
azure-pipelines/Merge-CodeCoverage.ps1
azure-pipelines/artifacts/_all.ps1
azure-pipelines/artifacts/_pipelines.ps1
azure-pipelines/artifacts/_stage_all.ps1
azure-pipelines/artifacts/coverageResults.ps1
azure-pipelines/artifacts/testResults.ps1
azure-pipelines/dotnet-test-cloud.ps1
azure-pipelines/dotnet.yml
azure-pipelines/publish-CodeCov.ps1
azure-pipelines/publish-codecoverage.yml
azure-pipelines/release.yml
azure-pipelines/test.runsettings
azure-pipelines/variables/_all.ps1
azure-pipelines/variables/_pipelines.ps1
test/Directory.Build.targets
test/Nerdbank.Streams.Benchmark/Nerdbank.Streams.Benchmark.csproj
test/Nerdbank.Streams.Tests/Nerdbank.Streams.Tests.csproj
tools/Install-NuGetCredProvider.ps1

Also target .NET 6 in test projects instead of .NET 5.

Library.Template update

---

src/Nerdbank.Streams.Tests/MultiplexingStreamTests.cs
src/Nerdbank.Streams/MultiplexingStream.Channel.cs
src/Nerdbank.Streams/MultiplexingStream.cs

Fix MultiplexingStream failure when one Channel fails to pass data to reader

---

src/nerdbank-streams/yarn.lock
test/IsolatedTestHost/IsolatedTestHost.csproj
test/Nerdbank.Streams.Benchmark/Nerdbank.Streams.Benchmark.csproj
test/Nerdbank.Streams.Tests/Nerdbank.Streams.Tests.csproj

Apply latest Library.Template update

---

.config/dotnet-tools.json
.editorconfig
Directory.Packages.props
global.json
src/Nerdbank.Streams/PipeExtensions.cs
src/Nerdbank.Streams/Sequence`1.cs
src/Nerdbank.Streams/netstandard2.0/PublicAPI.Shipped.txt
src/Nerdbank.Streams/netstandard2.1/PublicAPI.Shipped.txt
tools/Install-DotNetSdk.ps1

- Fix ARM64 detection on Windows Powershell
- Bump up SDK and tools versions
- Copy the .config file when applying the template
- Upgrade `actions/checkout` GitHub action to v3
- Elevate CA1062 for shipping code
- Bump Nerdbank.GitVersioning to 3.6.128
- Fix compilation warnings

Merge latest Library.Template

---

.config/dotnet-tools.json
Directory.Packages.props
src/Nerdbank.Streams/README.md

Also merge latest Library.Template

Add package README

---

src/Nerdbank.Streams/WebSocketStream.cs

This is anticipated to resolve a deadlock that occurs with .NET Framework when it wraps this stream with another stream (e.g. `NegotiateStream`) that uses APM style async methods.
Closes #823

Override `WebSocketStream` APM style async methods

---

Directory.Packages.props
src/Nerdbank.Streams/Nerdbank.Streams.csproj
test/Nerdbank.Streams.Interop.Tests/Nerdbank.Streams.Interop.Tests.csproj
test/Nerdbank.Streams.Tests/Nerdbank.Streams.Tests.csproj

Ports #871 to stable v2.11 version

Drop the threading analyzers dependency

---

.github/workflows/build.yml
CODE-OF-CONDUCT.md

Fixes dotnet/org-policy-violations#6762
Fixes dotnet/org-policy-violations#6342
Fixes dotnet/org-policy-violations#5965
Fixes dotnet/org-policy-violations#5034

Switch back to DNF redirector URL
